# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: 'eviden_v1.$(Rev:rr)'

trigger: none
pr: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'sergioprgm/astro'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(Build.BuildNumber)
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1 (0b6b4c37-f1bf-4ce2-a367-85ec50c803ea)'
        appType: 'webAppContainer'
        WebAppName: 'eviden-exam'
        DockerNamespace: 'docker.io'
        DockerRepository: 'sergioprgm/astro'
        DockerImageTag: '$(Build.BuildNumber)'
