name: Name test

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches: 
      - main

jobs:
    build:
        name: Test Commit Message
        runs-on: ubuntu-latest
        if: ${{ startsWith(github.event.head_commit.message, 'Test:') || startsWith(github.event.pull_request.title, 'Test:') }}
        steps:
        - run: echo "Commit => ${{ github.event.head_commit.message }}"
        - run: echo "PR Title => ${{ github.event.pull_request.title }}"
