name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches: 
      - main

jobs:
  test: 
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Update:')
    # if: contains(github.event.head_commit.message, 'Update')
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "💡 The ${{ github.repository }} repository is working correctly"
    - run: echo "Finishing job"
    - run: echo "Commit message: ${{ github.event.head_commit.message }}"
  
